# Generated by BehavEd
# ( "start da fight" )
setDefaultTarget("tiger02" )
setAIActive("tiger02", "TRUE" )
setAIActive("attuma02", "TRUE" )
waittimed ( 0.100 )
setPatternSequence("tiger02", "inflow" )
setPatternSequence("attuma02", "inflow" )

