# Generated by BehavEd
# ( "tiger shark and attuma boss battle intro" )
met = getGameFlag("bosses", 5 )
setRecallActive("FALSE" )
setMusicOverride("music/sea4_x", 1.000 )
setEnable("arena_trigger", "TRUE" )
if met == 0
     setGameFlag("bosses", 5, 1 )
     startCutScene("FALSE", "FALSE" )
     cameraMove(" 3960.190 5323.220 -22.800 ", 0.500 )
     cameraPan(" 0.000 17.400 89.400 ", 0.500, "FALSE" )
     waittimed ( 0.500 )
     endCutScene("FALSE", "FALSE" )
     startConversation("act1/atlantis/atlantis4/1_ATLANTIS4_030" )
else
     waittimed ( 0.200 )
     setDefaultTarget("tiger02" )
     setAIActive("tiger02", "TRUE" )
     setAIActive("attuma02", "TRUE" )
     waittimed ( 0.100 )
     setPatternSequence("tiger02", "inflow" )
     setPatternSequence("attuma02", "inflow" )
endif

